plugins { id 'com.android.application' }
android {
    namespace 'de.mkrativ.crocosauf'
    compileSdk 35
    defaultConfig {
        applicationId 'de.mkrativ.crocosauf'
        minSdk 26
        targetSdk 35
        versionCode 2
        versionName '1.1'
        testInstrumentationRunner 'de.mkrativ.crocosauf.SettingsInstrumentation'
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    buildTypes { release { minifyEnabled false } }
    lint { abortOnError true }
}
